### ISSUE TITLE
macOS related build failure

### ISSUE THREAD

**Issue by mks2183** [apache/nuttx#9850] opened 2023-07-18 05:40 UTC
Hi All,

I am seeing error in build where PR #9846. Is it something related with macOS ? Did anybody face it ?

Regards,
Manish

**Comment by acassis** [comment] 2023-07-18 13:13
@mks2183 I think the issue is related to some MacOS downloaded file. I don't know much about the CI, but maybe we need to create a dedicated mirror to avoid these frequent errors on MacOS.

**Comment by btashton** [comment] 2023-07-18 13:54
> @mks2183 I think the issue is related to some MacOS downloaded file. I don't know much about the CI, but maybe we need to create a dedicated mirror to avoid these frequent errors on MacOS.

As I have said before this error has nothing to do with downloading a file. Why do you keep saying that.  There is no world where we should be mirroring pypi.

**Comment by acassis** [comment] 2023-07-18 14:57
You are right @btashton, this is not related to download timeout or similar as in the past, seems like some modification in the pypi files itself. But having a controlled mirror we could make the packages fixed or only update when after testing some staging CI before updating to use in the main CI.

**Comment by mu578** [comment] 2023-07-18 15:33
This a cython 3.0 issue, it is broken within python 3.12 ; till today the only solution that is to get prev version install, meanwhile, I agree relaying on pip is tricky, I have that experience to bind a lot of numerical / ML /algebra algorithms from C to python using cython, I banned that package manager long ago, I do maintain my own toolchain separated, why? because it randomly breaks packages.

**Comment by xiaoxiang781216** [comment] 2023-07-18 18:44
Anyway, the ci is broken now. If nobody can fix it, I will disable macOS ci tomorrow.

**Comment by xiaoxiang781216** [comment] 2023-07-19 05:40
Fixed by https://github.com/apache/nuttx/pull/9855.

**Closed by xiaoxiang781216** 2023-07-19 05:40 UTC

**Comment by mu578** [comment] 2023-08-02 16:35
https://github.com/apache/nuttx/pull/9993#issuecomment-1662509586
