### ISSUE TITLE
unwind_frame has issues on arm cortext M7

### ISSUE THREAD

**Issue by gneworld** [apache/nuttx#12687] opened 2024-07-14 03:42 UTC
![image](https://github.com/user-attachments/assets/af0aa53d-5449-4311-8557-67a5e590ebc5)

During the backtrace process,  the system freezes, and the anomaly shown in the image above，such as lr is 0xFFFFFFFF and pc is 0xFFFFFFFC 

![image](https://github.com/user-attachments/assets/efc58b4b-be45-4115-98dc-f9d7252da1af)

When I add this conditional check,  the problem disappeared，so is this a real issue or how should I do to avoid this issue？

Now let's  simplify this problem with hello app，I find that when build with -O3, hello app would freezes during backtrace，but if we build it with -O0, hello app works well(with wrong pc value),  so  do  the -funwind-tables  have conflicts with -O3 in some cases ？

```
int main(int argc, FAR char *argv[])

 {
      _alert("sched_dumpstack ....\n");
      sched_dumpstack(0);
      _alert("sched_dumpstack ok\n");
      return 0;
 }
```

![image](https://github.com/user-attachments/assets/f08bbb8e-cf59-45bc-b436-c74abb267451)

**Comment by acassis** [comment] 2024-07-14 12:22
@gneworld probably it was caused by some function returning -1 to LR, what explain this 0xFFFFFFFF value.

Hi @anchao could you please help? I think you added support for it, right?

**Comment by anjiahao1** [comment] 2024-07-15 04:03
@gneworld 
<img width="1676" alt="image" src="https://github.com/user-attachments/assets/ed09d86d-f599-44d7-bf57-6e11dafad6de">
try it

**Comment by anjiahao1** [comment] 2024-07-15 04:05
Perhaps the above method is not a good method. The reason for this problem is that the idle thread needs to clear lr before calling nxstart, otherwise the unwind backtrace is likely to go wrong because the value of `lr` is uncertain before `__start`.

**Comment by gneworld** [comment] 2024-07-15 08:49
> Perhaps the above method is not a good method. The reason for this problem is that the idle thread needs to clear lr before calling nxstart, otherwise the unwind backtrace is likely to go wrong because the value of `lr` is uncertain before `__start`.

@anjiahao1  but why does -O0 work correctly, while -O3 does not?

**Comment by anchao** [comment] 2024-07-15 10:01
> Hi @anchao could you please help? I think you added support for it, right?

@acassis @anjiahao1 is more familiar with the details of unwind table backtrace than me.  @anjiahao1 @gneworld Aren't you guys on the same floor? why not confirm the issue offline?

**Comment by anjiahao1** [comment] 2024-07-15 10:07
The root cause is that at reset, the value of the general register is usually not fixed, and lr needs to be set to 0 before calling nxstart, which requires modifying a lot of arch/chips code

**Comment by anchao** [comment] 2024-07-15 11:42
1. Seems as expected, you need to confirm with vendor the behavior of **RAR(Reset all registers)** when lockstep is disabled, which is fixed on design phase.
2. Zephyr does something similar, I think initializing the registers is necessary
https://github.com/zephyrproject-rtos/zephyr/pull/20473

[ARM_ECM_0690721_Cortex_M33_DCLS.pdf](https://github.com/user-attachments/files/16233802/ARM_ECM_0690721_Cortex_M33_DCLS.pdf)

![20240715-194023](https://github.com/user-attachments/assets/8b59d6e7-9ba5-44f6-8ce9-4769b3d310d1)

**Comment by anchao** [comment] 2024-07-15 11:43
https://developer.arm.com/documentation/101773/0001/Functional-Description/CPU?lang=en

![20240715-194317](https://github.com/user-attachments/assets/2ada4797-b152-4d92-aa00-7789a7379b9e)

**Comment by acassis** [comment] 2024-07-15 13:04
> > Hi @anchao could you please help? I think you added support for it, right?
> 
> @acassis @anjiahao1 is more familiar with the details of unwind table backtrace than me. @anjiahao1 @gneworld Aren't you guys on the same floor? why not confirm the issue offline?

@anchao I think if they can do it at same room is fine, but please don't report the details here to let more people see what was the issue; how the root causes was discovered and why "that new commit" is the right solution :-)

**Comment by lywind** [comment] 2024-07-16 06:37
> 1. Seems as expected, you need to confirm with vendor the behavior of **RAR(Reset all registers)** when lockstep is disabled, which is fixed on design phase.
> 2. Zephyr does something similar, I think initializing the registers is necessary
>    [arch: arm: Rewrite Cortex-R reset vector function. zephyrproject-rtos/zephyr#20473](https://github.com/zephyrproject-rtos/zephyr/pull/20473)
> 
> [ARM_ECM_0690721_Cortex_M33_DCLS.pdf](https://github.com/user-attachments/files/16233802/ARM_ECM_0690721_Cortex_M33_DCLS.pdf)
> 
> ![20240715-194023](https://private-user-images.githubusercontent.com/758493/348691216-8b59d6e7-9ba5-44f6-8ce9-4769b3d310d1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMDY1MTksIm5iZiI6MTcyMTEwNjIxOSwicGF0aCI6Ii83NTg0OTMvMzQ4NjkxMjE2LThiNTlkNmU3LTliYTUtNDRmNi04Y2U5LTQ3NjliM2QzMTBkMS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNlQwNTAzMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMTI5N2E1MzUzMjEzN2NmODE1OTE0YjE5ZmY5Yzc3OGY0MDg0ZWNmOTU3N2QwNzM3OWU5Zjk3YmM2OTZkNjVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.o1cNZ0dyetb09TjLSEA19NCvTi7HnAhCNtMSIwrYNo8)

In fact, this is a Cortex-M7 MCU which is the ARM v7M-E architecture. And it does not have LOCKSTEP or RAR configurations. So I think it might not be the DCLS problem.

**Comment by anchao** [comment] 2024-07-16 08:06
> In fact, this is a Cortex-M7 MCU which is the ARM v7M-E architecture. And it does not have LOCKSTEP or RAR configurations. So I think it might not be the DCLS problem.

DCLS is configurable on Cortex-M7, I just suspect that the case they are facing is a issue on the lock-step core.

https://developer.arm.com/Processors/Cortex-M7

![20240716-160632](https://github.com/user-attachments/assets/af875480-2af4-42f0-842c-4ac59047749c)

**Comment by lywind** [comment] 2024-07-16 10:19
> > In fact, this is a Cortex-M7 MCU which is the ARM v7M-E architecture. And it does not have LOCKSTEP or RAR configurations. So I think it might not be the DCLS problem.
> 
> DCLS is configurable on Cortex-M7, I just suspect that the case they are facing is a issue on the lock-step core.
> 
> https://developer.arm.com/Processors/Cortex-M7
> 
> ![20240716-160632](https://private-user-images.githubusercontent.com/758493/348996832-af875480-2af4-42f0-842c-4ac59047749c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMjAwNDQsIm5iZiI6MTcyMTExOTc0NCwicGF0aCI6Ii83NTg0OTMvMzQ4OTk2ODMyLWFmODc1NDgwLTJhZjQtNDJmMC04NDJjLTRhYzU5MDQ3NzQ5Yy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNlQwODQ5MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jM2QyYmVkN2E5ZTk5ZmM2MzM5OGI2ODFjOTg3OGIxMjVjZWE2MDllODhkZGE5YjY3MWIxNjRmMWZjZmQ3ZjYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Lghuob-mBYL9rlpiELOk3eRSZrQH3zzyyH6v7yJBxQ8)

Double checked and it's comfirmed that the LOCKSTEP and RAR are both enabled. And I'm wondering why the function unwind_find_entry(frame->pc) does not return NULL when frame->pc == 0xFFFFFFFC? It's obvious that 0xFFFFFFFC exceeds __exidx_end.

**Comment by lywind** [comment] 2024-07-16 13:35
> @gneworld probably it was caused by some function returning -1 to LR, what explain this 0xFFFFFFFF value.
> 
> Hi @anchao could you please help? I think you added support for it, right?

The reason of the 0xFFFFFFFF being on the stack is that the compiler considers the __start as a normal function and pushes LR in the stack。
![image](https://github.com/user-attachments/assets/470a796c-b161-445f-9ba1-a0c32224e5b5)
And when the core boots from reset, the core will set LR to 0xFFFFFFFF.
![image](https://github.com/user-attachments/assets/27e26715-a58a-4dce-a2be-5edf2960e8d4)
B1.5.5 of Arm®v7-M Architecture Reference Manual

**Comment by anchao** [comment] 2024-07-17 01:31
I'm not sure if the `naked` attribute could avoid this issue, which ensures that the unwind `extab` does not contain any push content:

```
diff --git a/include/nuttx/init.h b/include/nuttx/init.h
index af3dce335f..98b9ba68f8 100644
--- a/include/nuttx/init.h
+++ b/include/nuttx/init.h
@@ -98,7 +98,7 @@ EXTERN uint8_t g_nx_initstate;  /* See enum nx_initstate_e */
 
 /* OS entry point called by boot logic */
 
-void nx_start(void);
+void nx_start(void) noreturn_function naked_function;
 
 #undef EXTERN
 #ifdef __cplusplus

```

**Comment by gneworld** [comment] 2024-07-19 00:49
@anchao  Unfortunately, this change cannot solve the problem.

**Comment by anjiahao1** [comment] 2024-07-29 07:42
hello all, i ceate a pr fix it https://github.com/apache/nuttx/pull/12787

**Closed** 2024-07-29 14:19 UTC
