### ISSUE TITLE
ESP32-C6 devkit cannot be built

### ISSUE THREAD

**Issue by ronakmanani** [apache/nuttx#10820] opened 2023-09-27 09:25 UTC
Following commands were ran:

**/tools/configure.sh -l esp32c6-devkit:nsh**

**make**

Following error is received:

riscv64-unknown-elf-ld: /opt/riscv/lib/gcc/riscv64-unknown-elf/12.2.0/libgcc.a(div.o): ABI is incompatible with that of the selected emulation:
  target emulation `elf64-littleriscv' does not match `elf32-littleriscv'

I read a post for FreeRTOS where we need to add the flags -march= rv32imac -mabi=ilp32. But I am unable to find the Linker and compiler flags.

As already mentioned, I am trying to use them for ESP32c6 devkit.

**Comment by tmedicci** [comment] 2023-09-27 09:49
Hi!

According to https://nuttx.apache.org/docs/latest/platforms/risc-v/esp32c6/index.html, it's recommended to use the [SiFive's toolchain](https://github.com/sifive/freedom-tools/releases). Please, consider using it for building C6.

**Comment by pkarashchenko** [comment] 2023-09-27 09:59
Also the toolchain from Espressif should work, but I didn't try it recently

**Comment by znmeb** [comment] 2024-04-09 18:35
I'm having problems with the ESP32-C3 devkit as well. I've tried the xPack RISC-V tools recommended in the documentation and they don't work. Neither do the RISC-V tools in Ubuntu 22.04, Either the documentation is wrong or the tools don't work.

**Comment by tmedicci** [comment] 2024-04-09 20:05
> I'm having problems with the ESP32-C3 devkit as well. I've tried the xPack RISC-V tools recommended in the documentation and they don't work. Neither do the RISC-V tools in Ubuntu 22.04, Either the documentation is wrong or the tools don't work.

Hi @znmeb . The recommended toolchain is used by both the NuttX CI and Espressif's internal CI. Also, the docker image used by both CIs are based on Ubuntu 22.04. Could you please share the error you found?

**Comment by znmeb** [comment] 2024-04-09 21:28
The error I was getting was that it couldn't find `riscv64-none-elf-gcc`. But that seems to have gone away. I'll try to reproduce it later tonight.

**Comment by znmeb** [comment] 2024-04-09 23:49
Looks like I can't reproduce it - I'm running a script over all the `esp32c3-devkit` configurations at the moment and it hasn't failed yet. I'll post again once it gets through all of them.

**Comment by znmeb** [comment] 2024-04-10 04:02
My test script successfully built all of the ESP32-S3 and ESP32-C3 devkit configurations. By the way, the way I'm now installing the tools is as follows: 

1. Do a `docker build` on `nuttx/tools/ci/docker/linux/Dockerfile`
2. Create a container from the Docker image
3. Do a `docker cp` from the container to my filesystem.

The build takes some time but it only needs to be done once unless there are changes in the upstream files.

I've got a couple of ESP32-C6 boards on order; I'll test the builds when they show up.

**Comment by tmedicci** [comment] 2024-04-10 12:03
Alright, since the original issue is gone, I'll close this issue. Please, let us know if you find any trouble...

**Closed by tmedicci** 2024-04-10 12:03 UTC
