### ISSUE TITLE
trace not working on rv-virt:knsh64?

### ISSUE THREAD

**Issue by GooTal** [apache/nuttx#9273] opened 2023-05-15 02:51 UTC
I did as [task trace user guide](https://nuttx.apache.org/docs/latest/guides/tasktraceuser.html) told. Enabled these configuration:
![图片](https://github.com/apache/nuttx/assets/40800103/3cadfbbe-b0d5-4ea7-8187-4d1c2343e1ed)

I also enabled these configuration:
```
CONFIG_TRACE=y
CONFIG_TRACE_ARCH=y
CONFIG_TRACE_AUDIO=y
CONFIG_TRACE_BOARDS=y
CONFIG_TRACE_CRYPTO=y
CONFIG_TRACE_DRIVERS=y
CONFIG_TRACE_FS=y
CONFIG_TRACE_GRAPHICS=y
CONFIG_TRACE_LIBS=y
CONFIG_TRACE_NET=y
CONFIG_TRACE_SCHED=y
CONFIG_TRACE_VIDEO=y
CONFIG_TRACE_WIRELESS=y
```

Then i built rv-virt:knsh64 from branch releases/12.1. But trace is still not found.
![图片](https://github.com/apache/nuttx/assets/40800103/af47ba5b-0b31-4d36-979b-0791eaed9104)

Thanks if you could help.

**Comment by xiaoxiang781216** [comment] 2023-05-15 03:13
you need turn on CONFIG_SYSTEM_TRACE to get the trace command.

**Comment by GooTal** [comment] 2023-05-15 03:30
Yes, i have turned it on. Exactly as [task trace user guide](https://nuttx.apache.org/docs/latest/guides/tasktraceuser.html) told.

![图片](https://github.com/apache/nuttx/assets/40800103/ff4123c5-5007-4d3a-859c-be441f3c6754)

But rv-virt:knsh64 is not working. 
![图片](https://github.com/apache/nuttx/assets/40800103/11e15cd4-8b9b-450b-a7db-92918a9e563e)

BTW, rv-virt:nsh64 (flat build) works fine. Is there something wrong with kernel build?

**Comment by xiaoxiang781216** [comment] 2023-05-15 04:04
@GooTal are you looking the opportunity of internship?

**Comment by xiaoxiang781216** [comment] 2023-05-15 04:07
> BTW, rv-virt:nsh64 (flat build) works fine. Is there something wrong with kernel build?

do you mount hostfs? trace should be put into apps/bin/ folder, you may need luanch the program with the full path.

**Comment by GooTal** [comment] 2023-05-15 06:25
> @GooTal are you looking the opportunity of internship?

Yes i have been looking for the opportunity of intership. But the tutor does not allow us to have summer intership. :( 
Maybe i could get in touch with the mentor or HRs of companies by submitting my resume.

**Comment by GooTal** [comment] 2023-05-15 06:29
> > BTW, rv-virt:nsh64 (flat build) works fine. Is there something wrong with kernel build?
> 
> do you mount hostfs? trace should be put into apps/bin/ folder, you may need luanch the program with the full path.

Yes, i mounted hostfs. I could use the `cat /host/AUTHORS` cmd to read the authors.
And trace is successfully compiled and put into apps/bin/ folder.
![图片](https://github.com/apache/nuttx/assets/40800103/408ea7ba-aec4-4841-9541-41a96584dcea)

![图片](https://github.com/apache/nuttx/assets/40800103/f1f4be82-2847-47e4-9c91-78ceb60276c0)

And hello works fine. trace still not working.
![图片](https://github.com/apache/nuttx/assets/40800103/d0751150-567f-41e1-bd2f-81a1bebfc8bc)

**Comment by GooTal** [comment] 2023-05-15 07:33
Oh, it called task_spawn [here](https://github.com/apache/nuttx-apps/blob/0acd68b391244d8edf5c3bc78e2b0ce818868a5b/system/system/system.c#L139), which is not supported for kernel build.
![图片](https://github.com/apache/nuttx/assets/40800103/2db6ded7-a6c8-4367-9fad-cc4b5ad0f9e7)

So the kernel build requires CONFIG_SYSTEM_SYSTEM_SHPATH to enable posix_spawn [here](https://github.com/apache/nuttx-apps/blob/0acd68b391244d8edf5c3bc78e2b0ce818868a5b/system/system/system.c#LL135C8-L135C35). 

Additionally, CONFIG_SYSTEM_SYSTEM_SHPATH depends on `SYSTEM_NSH=m` [here](https://github.com/apache/nuttx-apps/blob/0acd68b391244d8edf5c3bc78e2b0ce818868a5b/system/system/Kconfig#L20) , which was `SYSTEM_NSH=y` previously.

So i changed SYSTEM_NSH=m and enabled CONFIG_SYSTEM_SYSTEM_SHPATH. Problem solved for rv-virt:knsh64.

**Comment by GooTal** [comment] 2023-05-15 10:58
Thanks a lot. I\`ve sent my wechat number to your gmail.

**Comment by xiaoxiang781216** [comment] 2023-05-29 18:09
The problem is resolved, let's close it now.

**Closed by xiaoxiang781216** 2023-05-29 18:09 UTC
